name: Deploy Next.js to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3  # Updated to v3

      - name: Setup Node.js
        uses: actions/setup-node@v3  # Updated to v3
        with:
          node-version: 18  # Updated to Node 18 (LTS)

      - name: Install Dependencies
        run: npm ci  # Use ci for clean install

      - name: Build Project
        run: npm run build

      - name: Export Static Site
        run: npm run export  # Add this if you have "export" script in package.json

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./out  # Changed from build to out (Next.js default)
          keep_files: true  # Keep existing files in gh-pages branch